// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netmonSockVal struct {
	_    structs.HostLayout
	Ts   uint64
	Pid  uint32
	Comm [16]int8
	Pad  uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	netmonMapConns           = "conns"
	netmonMapEvents          = "events"
	netmonMapPending         = "pending"
	netmonProgHandleSetState = "handle_set_state"
	netmonVarUnusedEvent     = "unused_event"
)

// loadNetmon returns the embedded CollectionSpec for netmon.
func loadNetmon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetmonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netmon: %w", err)
	}

	return spec, err
}

// loadNetmonObjects loads netmon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netmonObjects
//	*netmonPrograms
//	*netmonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetmonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetmon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netmonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonSpecs struct {
	netmonProgramSpecs
	netmonMapSpecs
	netmonVariableSpecs
}

// netmonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonProgramSpecs struct {
	HandleSetState *ebpf.ProgramSpec `ebpf:"handle_set_state"`
}

// netmonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonMapSpecs struct {
	Conns   *ebpf.MapSpec `ebpf:"conns"`
	Events  *ebpf.MapSpec `ebpf:"events"`
	Pending *ebpf.MapSpec `ebpf:"pending"`
}

// netmonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netmonVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// netmonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonObjects struct {
	netmonPrograms
	netmonMaps
	netmonVariables
}

func (o *netmonObjects) Close() error {
	return _NetmonClose(
		&o.netmonPrograms,
		&o.netmonMaps,
	)
}

// netmonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonMaps struct {
	Conns   *ebpf.Map `ebpf:"conns"`
	Events  *ebpf.Map `ebpf:"events"`
	Pending *ebpf.Map `ebpf:"pending"`
}

func (m *netmonMaps) Close() error {
	return _NetmonClose(
		m.Conns,
		m.Events,
		m.Pending,
	)
}

// netmonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// netmonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetmonObjects or ebpf.CollectionSpec.LoadAndAssign.
type netmonPrograms struct {
	HandleSetState *ebpf.Program `ebpf:"handle_set_state"`
}

func (p *netmonPrograms) Close() error {
	return _NetmonClose(
		p.HandleSetState,
	)
}

func _NetmonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netmon_bpfel.o
var _NetmonBytes []byte
